name: Refresh Filtered Feeds

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser pyyaml

      - name: Refresh filtered feeds
        run: python filter_podcast_feed.py

      - name: Commit and push refreshed feeds
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.xml
          git commit -m "Refreshed filtered feed(s)" || echo "No changes to commit"
          git push
